In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
url_file=f"result/lsr_std_mip_first_feasible.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_first_feasible = table
table_first_feasible = table_first_feasible[['instance','objval','time']]
table_first_feasible

       instance    objval  time
0      52_1.txt   12770.8   0.0
1      52_2.txt   12827.8   0.0
2      52_3.txt   13398.0   0.0
3      52_4.txt   13413.4   0.0
4      52_5.txt   13936.5   0.0
..          ...       ...   ...
103  52_104.txt  119959.5   0.0
104  52_105.txt  129011.2   0.0
105  52_106.txt  118980.0   0.0
106  52_107.txt  128970.4   0.0
107  52_108.txt  119152.0   0.0

[108 rows x 3 columns]

In [70]:
url_file=f"result/lsr_std_mip_first_feasible_tlimited_max.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_limited_max = table
table_feasible_limited_max

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8866.8   2746.38  0.69  2.71  32117.0    0
1      52_2.txt   9021.2   2514.24  0.72  2.71  32497.0    0
2      52_3.txt   8823.6   2616.95  0.70  2.71  31956.0    0
3      52_4.txt   9137.6   2691.43  0.71  2.71  31835.0    0
4      52_5.txt  10045.0   2894.75  0.71  2.71  36371.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  38116.0  19539.50  0.49  2.71  31618.0    0
104  52_105.txt  38776.4  20881.16  0.46  2.71  34644.0    0
105  52_106.txt  41786.2  19877.79  0.52  2.71  34435.0    0
106  52_107.txt  39306.6  20820.92  0.47  2.71  35185.0    0
107  52_108.txt  41325.2  19523.64  0.53  2.71  35701.0    0

[108 rows x 7 columns]

In [71]:
url_file=f"result/lsr_std_mip_first_feasible_tlimited_mean.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_limited_mean = table
table_feasible_limited_mean

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8987.0   2540.45  0.72  1.05  10403.0    0
1      52_2.txt   9197.4   2354.47  0.74  1.05  11672.0    0
2      52_3.txt   9061.6   2381.04  0.74  1.05  10344.0    0
3      52_4.txt   9353.4   2497.74  0.73  1.05  10779.0    0
4      52_5.txt  10223.5   2646.49  0.74  1.05  11679.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  38195.5  18463.81  0.52  1.05  11084.0    0
104  52_105.txt  38776.4  19846.03  0.49  1.05  11479.0    0
105  52_106.txt  41786.2  18782.20  0.55  1.05  11594.0    0
106  52_107.txt  39306.6  19694.19  0.50  1.05  11843.0    0
107  52_108.txt  41352.4  18349.32  0.56  1.05  11746.0    0

[108 rows x 7 columns]

In [72]:
url_file=f"result/lsr_std_rf_fop.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','rf','time_rf','fop','time_fop']
table['time_total'] = table['time_rf']+table['time_fop']

table_rf_fop = table
table_rf_fop

       instance       rf  time_rf      fop  time_fop  time_total
0      52_1.txt   8915.4     0.76   8751.6      1.02        1.78
1      52_2.txt   8908.0     0.82   8852.8      1.44        2.26
2      52_3.txt   8648.6     0.74   8631.4      0.81        1.55
3      52_4.txt   9227.0     0.80   9076.6      1.34        2.14
4      52_5.txt   9758.5     0.96   9758.5      1.26        2.22
..          ...      ...      ...      ...       ...         ...
103  52_104.txt  39973.5     0.36  38400.0      0.31        0.67
104  52_105.txt  40533.0     0.35  39099.8      0.31        0.66
105  52_106.txt  45220.6     0.39  41933.6      0.33        0.72
106  52_107.txt  39315.8     0.34  38988.2      0.30        0.64
107  52_108.txt  43407.2     0.38  40813.2      0.31        0.69

[108 rows x 6 columns]

In [73]:
table_resume = pd.DataFrame()
table_resume['dif1'] = table_rf_fop['fop'] - table_first_feasible['objval']
table_resume['dif2'] = table_rf_fop['fop'] - table_feasible_limited_mean['objval']
table_resume['dif3'] = table_rf_fop['fop'] - table_feasible_limited_max['objval']
table_resume

        dif1   dif2   dif3
0    -4019.2 -235.4 -115.2
1    -3975.0 -344.6 -168.4
2    -4766.6 -430.2 -192.2
3    -4336.8 -276.8  -61.0
4    -4178.0 -465.0 -286.5
..       ...    ...    ...
103 -81559.5  204.5  284.0
104 -89911.4  323.4  323.4
105 -77046.4  147.4  147.4
106 -89982.2 -318.4 -318.4
107 -78338.8 -539.2 -512.0

[108 rows x 3 columns]

In [75]:
positive_count_dif1 = (table_resume['dif1'] < 0).sum()
positive_count_dif2 = (table_resume['dif2'] < 0).sum()
positive_count_dif3 = (table_resume['dif3'] < 0).sum()
print(f"Ganho do fop em relacao ao mip first feasible: {positive_count_dif1}")
print(f"Ganho do fop em relacao ao mip first feasible tlimited mean: {positive_count_dif2}")
print(f"Ganho do fop em relacao ao mip first feasible tlimited max: {positive_count_dif3}")

Ganho do fop em relacao ao mip first feasible: 108
Ganho do fop em relacao ao mip first feasible tlimited mean: 74
Ganho do fop em relacao ao mip first feasible tlimited max: 57

In [76]:
def tabela_mip(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','objval','bound','gap','time','nodes','opt']
    table = table[['instance','bound','objval','gap','time','nodes','opt']]

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'bound':tab['bound'].mean(),
            'objval':tab['objval'].mean(),
            'gap':tab['gap'].mean(),
            'time':tab['time'].mean(),
            'nodes':tab['nodes'].mean(),
            'opt':tab['opt'].sum(),
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [77]:
def tabela_math(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','rf','time_rf','fop','time_fop']
    table['time_total'] = table['time_rf']+table['time_fop']

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'52_{i}.txt'].index,'grupo'] = set_
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'rf':tab['rf'].mean(),
            'time_rf':tab['time_rf'].mean(),
            'fop':tab['fop'].mean(),
            'time_fop':tab['time_fop'].mean(),
            'time_total':tab['time_total'].mean()
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [78]:
file=f"result/lsr_std_mip_first_feasible.txt"

table_first_feasible, table_first_feasible_ = tabela_mip(file)

In [79]:
file=f"result/lsr_std_mip_first_feasible_tlimeted.txt"

table_feasible_tlimeted, table_feasible_tlimeted_ = tabela_mip(file)

FileNotFoundError: [Errno 2] No such file or directory: 'result/lsr_std_mip_first_feasible_tlimeted.txt'

In [80]:
table_first_feasible = table_first_feasible[['instance','objval','time']]
table_first_feasible

  instance         objval  time
0    set01   14754.941667   0.0
1    set02   26266.233333   0.0
2    set03   81300.891667   0.0
3    set04   22182.416667   0.0
4    set05   32648.075000   0.0
5    set06   88007.666667   0.0
6    set07   58353.908333   0.0
7    set08   69422.383333   0.0
8    set09  122978.475000   0.0

In [81]:
table_feasible_tlimeted

  instance         bound        objval       gap  time         nodes  opt
0    set01   2573.651667  10083.566667  0.743333  1.01  10988.166667    0
1    set02   4365.729167  13940.325000  0.688333  1.01   9534.416667    0
2    set03  11957.641667  25185.516667  0.525833  1.01   9043.416667    0
3    set04   4221.205000  13236.283333  0.682500  1.01  10661.666667    0
4    set05   5638.932500  17470.816667  0.675833  1.01  10675.583333    0
5    set06  13290.620000  28617.008333  0.535833  1.01   9887.416667    0
6    set07  10613.084167  20579.516667  0.479167  1.01  10385.750000    0
7    set08  11882.562500  25101.200000  0.524167  1.01  11131.333333    0
8    set09  18308.397500  37177.308333  0.506667  1.01  10752.250000    0

In [82]:
file=f"result/lsr_std_rf_fop.txt"

table_result_math, table_math = tabela_math(file)

In [83]:
table_result_math

  instance            rf   time_rf           fop  time_fop  time_total
0    set01   9856.975000  0.864167   9780.791667  1.320000    2.184167
1    set02  13979.708333  0.571667  13671.116667  0.637500    1.209167
2    set03  26252.875000  0.371667  25008.058333  0.261667    0.633333
3    set04  13128.091667  0.585833  13009.166667  0.713333    1.299167
4    set05  17366.633333  0.564167  17100.825000  0.764167    1.328333
5    set06  29714.858333  0.386667  28358.950000  0.282500    0.669167
6    set07  21004.725000  0.385833  20639.341667  0.334167    0.720000
7    set08  25575.975000  0.383333  25174.500000  0.391667    0.775000
8    set09  39140.933333  0.341667  37463.975000  0.289167    0.630833

In [84]:
file=f"result/lsr_std_mip_first_feasible_tlimeted.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

tab = pd.DataFrame()
tab = pd.concat([tab, df], ignore_index=True)
tab.columns = ['instance','bound','objval','gap','time','nodes','opt']

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=["resume"]
)

tab = pd.concat([tab, resume], ignore_index=True)

tab_mip = tab
tab_mip

FileNotFoundError: [Errno 2] No such file or directory: 'result/lsr_std_mip_first_feasible_tlimeted.txt'

In [85]:
set_ = 'set01'

tab = pd.DataFrame()
for i in range(1,13):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set01']
)

set01_mip = tab
#set01_mip

In [86]:
set_ = 'set02'

tab = pd.DataFrame()
for i in range(13,25):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set02']
)

set02_mip = tab
#set02_mip

In [87]:
set_ = 'set03'

tab = pd.DataFrame()
for i in range(25,37):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set03']
)

set03_mip = tab
#set03_mip

In [88]:
set_ = 'set04'

tab = pd.DataFrame()
for i in range(37,49):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set04']
)


set04_mip = tab
#set04_mip

In [89]:
set_ = 'set05'

tab = pd.DataFrame()
for i in range(49,61):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set05']
)

set05_mip = tab
#set05_mip

In [90]:
set_ = 'set06'

tab = pd.DataFrame()
for i in range(61,73):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set06']
)

set06_mip = tab
#set06_mip

In [91]:
set_ = 'set07'

tab = pd.DataFrame()
for i in range(73,85):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set07']
)

set07_mip = tab
#set07_mip

In [92]:
set_ = 'set08'

tab = pd.DataFrame()
for i in range(85,97):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set08']
)

set08_mip = tab
#set08_mip

In [93]:
set_ = 'set09'

tab = pd.DataFrame()
for i in range(97,109):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set09']
)

set09_mip = tab
#set09_mip

In [94]:
res_mip = pd.DataFrame()
res_mip = pd.concat([res_mip,set01_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set02_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set03_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set04_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set05_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set06_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set07_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set08_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set09_mip], ignore_index= True)
#res_mip

In [ ]:
tab = pd.DataFrame({
    'instance':f'res_mip',
    'bound':res_mip['bound'].mean(),
    'objval':res_mip['objval'].mean(),
    'gap':res_mip['gap'].mean(),
    'time':res_mip['time'].mean(),
    'nodes':res_mip['nodes'].mean(),
    'opt':res_mip['opt'].sum(),
    },index=[f'res_mip']
)

res_mip = pd.concat([res_mip, tab], ignore_index=True)
#res_mip

print(res_mip[['instance','objval','bound','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrrr}
\toprule
instance & objval & bound & gap & time & nodes & opt \\
\midrule
set01 & 2573.65 & 10083.57 & 0.74 & 1.01 & 10988.17 & 0 \\
set02 & 4365.73 & 13940.32 & 0.69 & 1.01 & 9534.42 & 0 \\
set03 & 11957.64 & 25185.52 & 0.53 & 1.01 & 9043.42 & 0 \\
set04 & 4221.21 & 13236.28 & 0.68 & 1.01 & 10661.67 & 0 \\
set05 & 5638.93 & 17470.82 & 0.68 & 1.01 & 10675.58 & 0 \\
set06 & 13290.62 & 28617.01 & 0.54 & 1.01 & 9887.42 & 0 \\
set07 & 10613.08 & 20579.52 & 0.48 & 1.01 & 10385.75 & 0 \\
set08 & 11882.56 & 25101.20 & 0.52 & 1.01 & 11131.33 & 0 \\
set09 & 18308.40 & 37177.31 & 0.51 & 1.01 & 10752.25 & 0 \\
res_mip & 9205.76 & 21265.73 & 0.60 & 1.01 & 10340.00 & 0 \\
\bottomrule
\end{tabular}

: