In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
url_file=f"result/lsr_std_mip_first_feasible.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_first_feasible = table
table_first_feasible = table_first_feasible[['instance','objval','time']]
table_first_feasible

       instance    objval  time
0      52_1.txt   12770.8   0.0
1      52_2.txt   12827.8   0.0
2      52_3.txt   13398.0   0.0
3      52_4.txt   13413.4   0.0
4      52_5.txt   13936.5   0.0
..          ...       ...   ...
103  52_104.txt  119959.5   0.0
104  52_105.txt  129011.2   0.0
105  52_106.txt  118980.0   0.0
106  52_107.txt  128970.4   0.0
107  52_108.txt  119152.0   0.0

[108 rows x 3 columns]

In [3]:
url_file=f"result/lsr_std_mip_first_feasible_tlimited_mean.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_tlimited_mean = table
table_feasible_tlimited_mean

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8987.0   2540.45  0.72  1.05  10403.0    0
1      52_2.txt   9197.4   2354.47  0.74  1.05  11672.0    0
2      52_3.txt   9061.6   2381.04  0.74  1.05  10344.0    0
3      52_4.txt   9353.4   2497.74  0.73  1.05  10779.0    0
4      52_5.txt  10223.5   2646.49  0.74  1.05  11679.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  38195.5  18463.81  0.52  1.05  11084.0    0
104  52_105.txt  38776.4  19846.03  0.49  1.05  11479.0    0
105  52_106.txt  41786.2  18782.20  0.55  1.05  11594.0    0
106  52_107.txt  39306.6  19694.19  0.50  1.05  11843.0    0
107  52_108.txt  41352.4  18349.32  0.56  1.05  11746.0    0

[108 rows x 7 columns]

In [4]:
url_file=f"result/lsr_std_mip_first_feasible_tlimited_max.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_tlimited_max = table
table_feasible_tlimited_max

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8866.8   2746.38  0.69  2.71  32117.0    0
1      52_2.txt   9021.2   2514.24  0.72  2.71  32497.0    0
2      52_3.txt   8823.6   2616.95  0.70  2.71  31956.0    0
3      52_4.txt   9137.6   2691.43  0.71  2.71  31835.0    0
4      52_5.txt  10045.0   2894.75  0.71  2.71  36371.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  38116.0  19539.50  0.49  2.71  31618.0    0
104  52_105.txt  38776.4  20881.16  0.46  2.71  34644.0    0
105  52_106.txt  41786.2  19877.79  0.52  2.71  34435.0    0
106  52_107.txt  39306.6  20820.92  0.47  2.71  35185.0    0
107  52_108.txt  41325.2  19523.64  0.53  2.71  35701.0    0

[108 rows x 7 columns]

In [5]:
url_file=f"result/lsr_std_rf_fop.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','rf','time_rf','fop','time_fop']
table['time_total'] = table['time_rf']+table['time_fop']

table_rf_fop = table
table_rf_fop

       instance       rf  time_rf      fop  time_fop  time_total
0      52_1.txt   8915.4     0.76   8751.6      1.02        1.78
1      52_2.txt   8908.0     0.82   8852.8      1.44        2.26
2      52_3.txt   8648.6     0.74   8631.4      0.81        1.55
3      52_4.txt   9227.0     0.80   9076.6      1.34        2.14
4      52_5.txt   9758.5     0.96   9758.5      1.26        2.22
..          ...      ...      ...      ...       ...         ...
103  52_104.txt  39973.5     0.36  38400.0      0.31        0.67
104  52_105.txt  40533.0     0.35  39099.8      0.31        0.66
105  52_106.txt  45220.6     0.39  41933.6      0.33        0.72
106  52_107.txt  39315.8     0.34  38988.2      0.30        0.64
107  52_108.txt  43407.2     0.38  40813.2      0.31        0.69

[108 rows x 6 columns]

In [6]:
print(np.round(table_rf_fop['time_total'].max(),2))
print(np.round(table_rf_fop['time_total'].mean(),2))

2.71
1.05

In [7]:
table_resume = pd.DataFrame()
table_resume['dif1'] = table_first_feasible['objval'] - table_rf_fop['fop']
table_resume['dif2'] = table_feasible_tlimited_mean['objval'] - table_rf_fop['fop']
table_resume['dif3'] = table_feasible_tlimited_max['objval'] - table_rf_fop['fop']
table_resume

        dif1   dif2   dif3
0     4019.2  235.4  115.2
1     3975.0  344.6  168.4
2     4766.6  430.2  192.2
3     4336.8  276.8   61.0
4     4178.0  465.0  286.5
..       ...    ...    ...
103  81559.5 -204.5 -284.0
104  89911.4 -323.4 -323.4
105  77046.4 -147.4 -147.4
106  89982.2  318.4  318.4
107  78338.8  539.2  512.0

[108 rows x 3 columns]

In [ ]:
positive_count_dif1 = (table_resume['dif1'] > 0).sum()
positive_count_dif2 = (table_resume['dif2'] > 0).sum()
positive_count_dif3 = (table_resume['dif3'] > 0).sum()
print(f"Positive values in column 'dif1': {positive_count_dif1}")
print(f"Positive values in column 'dif2': {positive_count_dif2}")
print(f"Positive values in column 'dif3': {positive_count_dif3}")

Positive values in column 'dif1': 108
Positive values in column 'dif2': 74
Positive values in column 'dif3': 57

:

In [9]:
def tabela_mip(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','objval','bound','gap','time','nodes','opt']
    table = table[['instance','bound','objval','gap','time','nodes','opt']]

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'c52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'c52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'bound':tab['bound'].mean(),
            'objval':tab['objval'].mean(),
            #'gap':tab.loc[table['opt'] == 0,'gap'].mean(),
            #'time':tab.loc[table['opt'] == 1,'time'].mean(),
            'gap':tab['gap'].mean(),
            'time':tab['time'].mean(),
            'nodes':tab['nodes'].mean(),
            'opt':tab['opt'].sum(),
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [10]:
def tabela_math(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','rf','time_rf','fop','time_fop']
    table['time_total'] = table['time_rf']+table['time_fop']

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'c52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'c52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'rf':tab['rf'].mean(),
            'time_rf':tab['time_rf'].mean(),
            'fop':tab['fop'].mean(),
            'time_fop':tab['time_fop'].mean(),
            'time_total':tab['time_total'].mean()
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [11]:
file=f"result/lsr_std_mip_first_feasible.txt"

table_first_feasible, table_first_feasible_ = tabela_mip(file)

In [12]:
file=f"result/lsr_std_mip_first_feasible_tlimeted.txt"

table_feasible_tlimeted, table_feasible_tlimeted_ = tabela_mip(file)

FileNotFoundError: [Errno 2] No such file or directory: 'result/lsr_std_mip_first_feasible_tlimeted.txt'

In [13]:
table_first_feasible = table_first_feasible[['instance','objval','time']]
table_first_feasible

  instance  objval  time
0    set01     NaN   NaN
1    set02     NaN   NaN
2    set03     NaN   NaN
3    set04     NaN   NaN
4    set05     NaN   NaN
5    set06     NaN   NaN
6    set07     NaN   NaN
7    set08     NaN   NaN
8    set09     NaN   NaN

In [15]:
table_feasible_tlimited

NameError: name 'table_feasible_tlimited' is not defined

In [16]:
file=f"result/lsr_std_rf_fop.txt"

table_result_math, table_math = tabela_math(file)

In [17]:
table_result_math

  instance  rf  time_rf  fop  time_fop  time_total
0    set01 NaN      NaN  NaN       NaN         NaN
1    set02 NaN      NaN  NaN       NaN         NaN
2    set03 NaN      NaN  NaN       NaN         NaN
3    set04 NaN      NaN  NaN       NaN         NaN
4    set05 NaN      NaN  NaN       NaN         NaN
5    set06 NaN      NaN  NaN       NaN         NaN
6    set07 NaN      NaN  NaN       NaN         NaN
7    set08 NaN      NaN  NaN       NaN         NaN
8    set09 NaN      NaN  NaN       NaN         NaN

In [18]:
tab = pd.DataFrame({
    'instance':f'res_mip_std',
    #'lb':table_result_std['lb'].mean(),
    'ub':table_result_std['ub'].mean(),
    #'gap':table_result_std['gap'].mean(),
    'time':table_result_std['time'].mean(),
    #'nodes':table_result_std['nodes'].mean(),
    'opt':table_result_std['opt'].sum(),
    },index=[f'res_mip_std']
)

res_mip_std = pd.concat([table_result_std, tab], ignore_index=True)
#res_mip_std

print(res_mip_std[['instance','ub','time']].to_latex(index=False,float_format="%.2f"))

NameError: name 'table_result_std' is not defined

In [20]:
file=f"result/lsr_std_mip.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

tab = pd.DataFrame()
tab = pd.concat([table, df], ignore_index=True)
tab.columns = ['instance','bound','objval','gap','time','nodes','opt']

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=["resume"]
)

tab = pd.concat([tab, resume], ignore_index=True)

mip_std = tab
#mip_std

FileNotFoundError: [Errno 2] No such file or directory: 'result/lsr_std_mip.txt'

In [ ]:
set_ = 'set01'

tab = pd.DataFrame()
for i in range(1,13):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set01']
)

set01_mip_sp = tab
#set01_mip_sp

In [ ]:
set_ = 'set02'

tab = pd.DataFrame()
for i in range(13,25):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set02']
)

set02_mip_sp = tab
#set02_mip_sp

In [ ]:
set_ = 'set03'

tab = pd.DataFrame()
for i in range(25,37):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set03']
)

set03_mip_std = tab
#set03_mip_std

In [ ]:
set_ = 'set04'

tab = pd.DataFrame()
for i in range(37,49):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set04']
)

set04_mip_std = tab
#set04_mip_std

In [ ]:
set_ = 'set05'

tab = pd.DataFrame()
for i in range(49,61):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set05']
)

set05_mip_std = tab
#set05_mip_std

In [ ]:
set_ = 'set06'

tab = pd.DataFrame()
for i in range(61,73):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set06']
)

set06_mip_std = tab
#set06_mip_std

In [ ]:
set_ = 'set07'

tab = pd.DataFrame()
for i in range(73,85):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set07']
)

set07_mip_sp = tab
#set07_mip_sp

In [ ]:
set_ = 'set08'

tab = pd.DataFrame()
for i in range(85,97):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set08']
)

set08_mip_std = tab
#set08_mip_std

In [ ]:
set_ = 'set09'

tab = pd.DataFrame()
for i in range(97,109):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set09']
)

set09_mip = tab
#set09_mip

In [ ]:
res_mip = pd.DataFrame()
res_mip = pd.concat([res_mip,set01_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set02_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set03_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set04_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set05_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set06_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set07_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set08_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set09_mip], ignore_index= True)
#res_mip

In [ ]:
tab = pd.DataFrame({
    'instance':f'res_mip_mc',
    'bound':res_mip_sp['bound'].mean(),
    'objval':res_mip_sp['objval'].mean(),
    'gap':res_mip_sp['gap'].mean(),
    'time':res_mip_sp['time'].mean(),
    'nodes':res_mip_sp['nodes'].mean(),
    'opt':res_mip_sp['opt'].sum(),
    },index=[f'res_mip_sp']
)

res_mip_sp = pd.concat([res_mip_sp, tab], ignore_index=True)
#res_mip_sp

print(res_mip_sp[['instance','bound','objval','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrrr}
\toprule
instance & lb & ub & gap & time & nodes & opt \\
\midrule
set01 & 10654.18 & 10262.92 & 0.04 & 3600.00 & 960238.58 & 0 \\
set02 & 17242.45 & 16693.90 & 0.03 & 3600.01 & 865838.92 & 0 \\
set03 & 48230.33 & 46836.73 & 0.03 & 3600.00 & 865817.50 & 0 \\
set04 & 14893.82 & 14436.87 & 0.03 & 3600.00 & 1084318.58 & 0 \\
set05 & 21858.60 & 21104.26 & 0.03 & 3600.00 & 887285.67 & 0 \\
set06 & 52945.74 & 51484.87 & 0.03 & 3600.00 & 768264.33 & 0 \\
set07 & 27721.93 & 27671.57 & 0.00 & 1101.85 & 667231.50 & 10 \\
set08 & 36907.85 & 36660.19 & 0.01 & 2457.01 & 923426.83 & 5 \\
set09 & 72934.06 & 71765.48 & 0.02 & 3600.01 & 1001321.17 & 0 \\
res_mip_mc & 33709.88 & 32990.76 & 0.02 & 3195.43 & 891527.01 & 15 \\
\bottomrule
\end{tabular}

In [ ]:

file=f"../clsr_std_mip.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

tab = pd.DataFrame()
tab = pd.concat([table, df], ignore_index=True)
tab.columns = ['instance','bound','objval','gap','time','nodes','opt']

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':table['bound'].mean(),
    'objval':table['objval'].mean(),
    'gap':table['gap'].mean(),
    'time':table['time'].mean(),
    'nodes':table['nodes'].mean(),
    'opt':table['opt'].sum(),
    },index=["resume"]
)

tab = pd.concat([tab, resume], ignore_index=True)

mip_std = tab
#mip_std

In [ ]:
set_ = 'set01'

tab = pd.DataFrame()
for i in range(1,13):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set01']
)

set01_mip_std = tab
#set01_mip_std

In [ ]:
set_ = 'set02'

tab = pd.DataFrame()
for i in range(13,25):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set02']
)

set02_mip_std = tab
#set02_mip_std

In [ ]:
set_ = 'set03'

tab = pd.DataFrame()
for i in range(25,37):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set03']
)

set03_mip_std = tab
#set03_mip_std

In [ ]:
set_ = 'set04'

tab = pd.DataFrame()
for i in range(37,49):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set04']
)


set04_mip_std = tab
#set04_mip_std

In [ ]:
set_ = 'set05'

tab = pd.DataFrame()
for i in range(49,61):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set05']
)

set05_mip_std = tab
#set05_mip_std

In [ ]:
set_ = 'set06'

tab = pd.DataFrame()
for i in range(61,73):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set06']
)

set06_mip_std = tab
#set06_mip_std

In [ ]:
set_ = 'set07'

tab = pd.DataFrame()
for i in range(73,85):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set07']
)

set07_mip_std = tab
#set07_mip_std

In [ ]:
set_ = 'set08'

tab = pd.DataFrame()
for i in range(85,97):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set08']
)

set08_mip_std = tab
#set08_mip_std

In [ ]:
set_ = 'set09'

tab = pd.DataFrame()
for i in range(97,109):
    t = mip_std.loc[mip_std['instance'] == f'c52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set09']
)

set09_mip_std = tab
#set09_mip_std

In [178]:
res_mip_std = pd.DataFrame()
res_mip_std = pd.concat([res_mip_std,set01_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set02_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set03_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set04_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set05_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set06_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set07_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set08_mip_std], ignore_index= True)
res_mip_std = pd.concat([res_mip_std,set09_mip_std], ignore_index= True)
#res_mip_std

In [ ]:
tab = pd.DataFrame({
    'instance':f'res_mip_std',
    'bound':res_mip_std['bound'].mean(),
    'objval':res_mip_std['objval'].mean(),
    'gap':res_mip_std['gap'].mean(),
    'time':res_mip_std['time'].mean(),
    'nodes':res_mip_std['nodes'].mean(),
    'opt':res_mip_std['opt'].sum(),
    },index=[f'res_mip_std']
)

res_mip_std = pd.concat([res_mip_std, tab], ignore_index=True)
#res_mip_std

print(res_mip_std[['instance','objval','bound','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

\begin{tabular}{lrrrrrr}
\toprule
instance & lb & ub & gap & time & nodes & opt \\
\midrule
set01 & 10641.49 & 10625.84 & 0.00 & 1247.22 & 691528.00 & 10 \\
set02 & 17222.92 & 17145.75 & 0.00 & 2313.22 & 1120619.92 & 7 \\
set03 & 48176.59 & 48046.57 & 0.00 & 2564.90 & 1128185.08 & 5 \\
set04 & 14875.52 & 14875.52 & 0.00 & 284.38 & 168174.50 & 12 \\
set05 & 21814.28 & 21783.95 & 0.00 & 1715.27 & 674848.17 & 10 \\
set06 & 52795.95 & 52643.11 & 0.00 & 2538.39 & 862585.25 & 6 \\
set07 & 27721.94 & 27721.94 & 0.00 & 2.88 & 3034.42 & 12 \\
set08 & 36906.27 & 36906.26 & 0.00 & 27.72 & 20063.67 & 12 \\
set09 & 72846.35 & 72670.70 & 0.00 & 1995.32 & 1135288.50 & 6 \\
res_mip_std & 33666.81 & 33602.18 & 0.00 & 1409.92 & 644925.28 & 80 \\
\bottomrule
\end{tabular}