In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
url_file=f"result/lsr_std_mip_feasible_first.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_first_feasible = table
table_first_feasible = table_first_feasible[['instance','objval','time']]
table_first_feasible

       instance    objval  time
0      52_1.txt   12770.8   0.0
1      52_2.txt   12827.8   0.0
2      52_3.txt   13398.0   0.0
3      52_4.txt   13413.4   0.0
4      52_5.txt   13936.5   0.0
..          ...       ...   ...
103  52_104.txt  119959.5   0.0
104  52_105.txt  129011.2   0.0
105  52_106.txt  118980.0   0.0
106  52_107.txt  128970.4   0.0
107  52_108.txt  119152.0   0.0

[108 rows x 3 columns]

In [3]:
url_file=f"result/lsr_std_mip_feasible_tlimited_max.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_limited_max = table
table_feasible_limited_max

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8710.2   2904.49  0.67  1.68  28593.0    0
1      52_2.txt   8929.6   2665.34  0.70  1.68  27264.0    0
2      52_3.txt   8842.8   2710.63  0.69  1.68  26465.0    0
3      52_4.txt   9305.6   2737.65  0.71  1.68  28149.0    0
4      52_5.txt  10006.0   2969.79  0.70  1.68  27089.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  37391.5  19482.38  0.48  1.68  32104.0    0
104  52_105.txt  39624.0  20100.23  0.49  1.68  32948.0    0
105  52_106.txt  41639.0  19966.41  0.52  1.68  34785.0    0
106  52_107.txt  39032.0  20923.13  0.46  1.68  34657.0    0
107  52_108.txt  41581.6  19460.79  0.53  1.68  34123.0    0

[108 rows x 7 columns]

In [4]:
url_file=f"result/lsr_std_mip_feasible_tlimited_mean.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_limited_mean = table
table_feasible_limited_mean

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8846.8   2678.03  0.70  0.65   9333.0    0
1      52_2.txt   9142.2   2461.23  0.73  0.65   9648.0    0
2      52_3.txt   8904.2   2481.87  0.72  0.65   8918.0    0
3      52_4.txt   9353.2   2537.17  0.73  0.65   9299.0    0
4      52_5.txt  10065.0   2721.31  0.73  0.65   9424.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  37391.5  18222.04  0.51  0.65   8678.0    0
104  52_105.txt  39655.0  18999.20  0.52  0.65  10240.0    0
105  52_106.txt  41639.0  18827.12  0.55  0.65  10962.0    0
106  52_107.txt  39236.4  19855.53  0.49  0.65  10699.0    0
107  52_108.txt  41604.4  18361.96  0.56  0.65  10780.0    0

[108 rows x 7 columns]

In [5]:
url_file=f"result/lsr_std_math.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','rf','time_rf','fop','time_fop']
table['time_total'] = table['time_rf']+table['time_fop']

table_math = table
table_math

       instance       rf  time_rf      fop  time_fop  time_total
0      52_1.txt   8915.4     0.49   8751.6      0.73        1.22
1      52_2.txt   8908.0     0.49   8852.8      0.94        1.43
2      52_3.txt   8648.6     0.46   8631.4      0.56        1.02
3      52_4.txt   9227.0     0.51   9076.6      0.96        1.47
4      52_5.txt   9758.5     0.57   9758.5      0.88        1.45
..          ...      ...      ...      ...       ...         ...
103  52_104.txt  39973.5     0.20  38400.0      0.20        0.40
104  52_105.txt  40533.0     0.19  39099.8      0.20        0.39
105  52_106.txt  45220.6     0.22  41933.6      0.21        0.43
106  52_107.txt  39315.8     0.19  38988.2      0.19        0.38
107  52_108.txt  43407.2     0.22  40813.2      0.20        0.42

[108 rows x 6 columns]

In [6]:
print(table_math['time_total'].max())
print(table_math['time_total'].mean())

1.6800000000000002
0.6518518518518519

In [7]:
table_resume = pd.DataFrame()
table_resume['dif1'] = table_math['fop'] - table_first_feasible['objval']
table_resume['dif2'] = table_math['fop'] - table_feasible_limited_mean['objval']
table_resume['dif3'] = table_math['fop'] - table_feasible_limited_max['objval']
table_resume

        dif1    dif2    dif3
0    -4019.2   -95.2    41.4
1    -3975.0  -289.4   -76.8
2    -4766.6  -272.8  -211.4
3    -4336.8  -276.6  -229.0
4    -4178.0  -306.5  -247.5
..       ...     ...     ...
103 -81559.5  1008.5  1008.5
104 -89911.4  -555.2  -524.2
105 -77046.4   294.6   294.6
106 -89982.2  -248.2   -43.8
107 -78338.8  -791.2  -768.4

[108 rows x 3 columns]

In [8]:
positive_count_dif1 = (table_resume['dif1'] < 0).sum()
positive_count_dif2 = (table_resume['dif2'] < 0).sum()
positive_count_dif3 = (table_resume['dif3'] < 0).sum()
print(f"Ganho do fop em relacao ao mip first feasible: {positive_count_dif1}")
print(f"Ganho do fop em relacao ao mip first feasible tlimited mean: {positive_count_dif2}")
print(f"Ganho do fop em relacao ao mip first feasible tlimited max: {positive_count_dif3}")

Ganho do fop em relacao ao mip first feasible: 108
Ganho do fop em relacao ao mip first feasible tlimited mean: 74
Ganho do fop em relacao ao mip first feasible tlimited max: 54

In [9]:
def tabela_mip(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','objval','bound','gap','time','nodes','opt']
    table = table[['instance','bound','objval','gap','time','nodes','opt']]

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'bound':tab['bound'].mean(),
            'objval':tab['objval'].mean(),
            'gap':tab['gap'].mean(),
            'time':tab['time'].mean(),
            'nodes':tab['nodes'].mean(),
            'opt':tab['opt'].sum(),
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [10]:
def tabela_math(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','rf','time_rf','fop','time_fop']
    table['time_total'] = table['time_rf']+table['time_fop']

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'52_{i}.txt'].index,'grupo'] = set_
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'rf':tab['rf'].mean(),
            'time_rf':tab['time_rf'].mean(),
            'fop':tab['fop'].mean(),
            'time_fop':tab['time_fop'].mean(),
            'time_total':tab['time_total'].mean()
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [11]:
file=f"result/lsr_std_mip_feasible_first.txt"

table_first_feasible, table_first_feasible_ = tabela_mip(file)

In [12]:
file=f"result/lsr_std_mip_feasible_tlimited_max.txt"

table_feasible_tlimited, table_feasible_tlimited_ = tabela_mip(file)

In [13]:
table_first_feasible = table_first_feasible[['instance','objval','time']]
table_first_feasible

  instance         objval  time
0    set01   14754.941667   0.0
1    set02   26266.233333   0.0
2    set03   81300.891667   0.0
3    set04   22182.416667   0.0
4    set05   32648.075000   0.0
5    set06   88007.666667   0.0
6    set07   58353.908333   0.0
7    set08   69422.383333   0.0
8    set09  122978.475000   0.0

In [14]:
table_feasible_tlimited

  instance         bound        objval       gap  time         nodes  opt
0    set01   2892.476667   9922.716667  0.707500  1.68  27745.083333    0
1    set02   4864.075000  13873.391667  0.649167  1.68  25964.833333    0
2    set03  13043.696667  24885.450000  0.475833  1.68  25552.000000    0
3    set04   4606.030000  13111.408333  0.649167  1.68  30005.416667    0
4    set05   6131.095833  17333.383333  0.645000  1.68  30811.916667    0
5    set06  14290.365833  28307.641667  0.495000  1.68  27246.500000    0
6    set07  11550.272500  20438.175000  0.429167  1.68  31210.083333    0
7    set08  12843.735833  25014.900000  0.487500  1.68  32393.916667    0
8    set09  19246.837500  37127.575000  0.479167  1.68  31872.250000    0

In [15]:
file=f"result/lsr_std_math.txt"

table_result_math, table_math = tabela_math(file)

In [16]:
table_result_math

  instance            rf   time_rf           fop  time_fop  time_total
0    set01   9856.975000  0.528333   9780.791667  0.888333    1.416667
1    set02  13979.708333  0.321667  13671.116667  0.411667    0.733333
2    set03  26252.875000  0.207500  25008.058333  0.160833    0.368333
3    set04  13128.091667  0.363333  13009.166667  0.488333    0.851667
4    set05  17366.633333  0.340000  17100.825000  0.514167    0.854167
5    set06  29714.858333  0.215833  28358.950000  0.175000    0.390833
6    set07  21004.725000  0.211667  20639.341667  0.210833    0.422500
7    set08  25575.975000  0.208333  25174.500000  0.246667    0.455000
8    set09  39140.933333  0.191667  37463.975000  0.182500    0.374167

In [17]:
file=f"result/lsr_std_mip.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

tab = pd.DataFrame()
tab = pd.concat([tab, df], ignore_index=True)
tab.columns = ['instance','bound','objval','gap','time','nodes','opt']

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=["resume"]
)

tab = pd.concat([tab, resume], ignore_index=True)

tab_mip = tab
tab_mip

,instance,bound,objval,gap,time,nodes,opt
0,52_1.txt,8698.800000,8698.800000,0.000000,12.090000,20827.00000,1
1,52_2.txt,8781.800000,8781.800000,0.000000,35.710000,92569.00000,1
2,52_3.txt,8541.600000,8541.600000,0.000000,4.370000,8093.00000,1
3,52_4.txt,8943.800000,8943.800000,0.000000,36.890000,95366.00000,1
4,52_5.txt,9717.000000,9717.000000,0.000000,201.020000,392059.00000,1
...,...,...,...,...,...,...,...
104,52_105.txt,38622.800000,38622.800000,0.000000,4.660000,3592.00000,1
105,52_106.txt,40310.400000,40310.400000,0.000000,10.800000,8824.00000,1
106,52_107.txt,38611.200000,38611.200000,0.000000,5.000000,4076.00000,1
107,52_108.txt,39826.200000,39826.200000,0.000000,3.250000,2114.00000,1
108,resume,20708.365741,20707.732407,0.000093,86.423889,147465.62963,107

In [18]:
set_ = 'set01'

tab = pd.DataFrame()
for i in range(1,13):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set01']
)

set01_mip = tab
#set01_mip

In [19]:
set_ = 'set02'

tab = pd.DataFrame()
for i in range(13,25):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set02']
)

set02_mip = tab
#set02_mip

In [20]:
set_ = 'set03'

tab = pd.DataFrame()
for i in range(25,37):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set03']
)

set03_mip = tab
#set03_mip

In [21]:
set_ = 'set04'

tab = pd.DataFrame()
for i in range(37,49):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set04']
)


set04_mip = tab
#set04_mip

In [22]:
set_ = 'set05'

tab = pd.DataFrame()
for i in range(49,61):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set05']
)

set05_mip = tab
#set05_mip

In [23]:
set_ = 'set06'

tab = pd.DataFrame()
for i in range(61,73):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set06']
)

set06_mip = tab
#set06_mip

In [24]:
set_ = 'set07'

tab = pd.DataFrame()
for i in range(73,85):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set07']
)

set07_mip = tab
#set07_mip

In [25]:
set_ = 'set08'

tab = pd.DataFrame()
for i in range(85,97):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set08']
)

set08_mip = tab
#set08_mip

In [26]:
set_ = 'set09'

tab = pd.DataFrame()
for i in range(97,109):
    t = tab_mip.loc[tab_mip['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'set09']
)

set09_mip = tab
#set09_mip

In [27]:
res_mip = pd.DataFrame()
res_mip = pd.concat([res_mip,set01_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set02_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set03_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set04_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set05_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set06_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set07_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set08_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set09_mip], ignore_index= True)
#res_mip

In [28]:
tab = pd.DataFrame({
    'instance':f'res_mip',
    'bound':res_mip['bound'].mean(),
    'objval':res_mip['objval'].mean(),
    'gap':res_mip['gap'].mean(),
    'time':res_mip['time'].mean(),
    'nodes':res_mip['nodes'].mean(),
    'opt':res_mip['opt'].sum(),
    },index=[f'res_mip']
)

res_mip = pd.concat([res_mip, tab], ignore_index=True)
res_mip

#print(res_mip[['instance','objval','bound','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

,instance,bound,objval,gap,time,nodes,opt
0,set01,9680.200000,9674.500000,0.000833,419.507500,723210.666667,11
1,set02,13530.833333,13530.833333,0.000000,161.103333,281019.250000,12
2,set03,24430.291667,24430.291667,0.000000,19.242500,25153.833333,12
3,set04,12843.641667,12843.641667,0.000000,10.765000,21227.250000,12
4,set05,16826.475000,16826.475000,0.000000,123.930000,226197.333333,12
5,set06,27706.900000,27706.900000,0.000000,35.277500,43102.750000,12
6,set07,20334.816667,20334.816667,0.000000,1.412500,1795.916667,12
7,set08,24661.750000,24661.750000,0.000000,2.180833,2259.500000,12
8,set09,36360.383333,36360.383333,0.000000,4.395833,3224.166667,12
9,res_mip,20708.365741,20707.732407,0.000093,86.423889,147465.629630,107