In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [71]:
url_file=f"result/lsr_std_mip_feasible_first.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_first_feasible = table
table_first_feasible = table_first_feasible[['instance','objval','time']]
table_first_feasible

       instance    objval  time
0      52_1.txt   12770.8   0.0
1      52_2.txt   12827.8   0.0
2      52_3.txt   13398.0   0.0
3      52_4.txt   13413.4   0.0
4      52_5.txt   13936.5   0.0
..          ...       ...   ...
103  52_104.txt  119959.5   0.0
104  52_105.txt  129011.2   0.0
105  52_106.txt  118980.0   0.0
106  52_107.txt  128970.4   0.0
107  52_108.txt  119152.0   0.0

[108 rows x 3 columns]

In [72]:
url_file=f"result/lsr_std_mip_feasible_first_tlimited_mean.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_tlimited_mean = table
table_feasible_tlimited_mean

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8987.0   2540.45  0.72  1.05  10403.0    0
1      52_2.txt   9197.4   2354.47  0.74  1.05  11672.0    0
2      52_3.txt   9061.6   2381.04  0.74  1.05  10344.0    0
3      52_4.txt   9353.4   2497.74  0.73  1.05  10779.0    0
4      52_5.txt  10223.5   2646.49  0.74  1.05  11679.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  38195.5  18463.81  0.52  1.05  11084.0    0
104  52_105.txt  38776.4  19846.03  0.49  1.05  11479.0    0
105  52_106.txt  41786.2  18782.20  0.55  1.05  11594.0    0
106  52_107.txt  39306.6  19694.19  0.50  1.05  11843.0    0
107  52_108.txt  41352.4  18349.32  0.56  1.05  11746.0    0

[108 rows x 7 columns]

In [73]:
url_file=f"result/lsr_std_mip_feasible_first_tlimited_max.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','objval','bound','gap','time','nodes','opt']

table_feasible_tlimited_max = table
table_feasible_tlimited_max

       instance   objval     bound   gap  time    nodes  opt
0      52_1.txt   8866.8   2746.38  0.69  2.71  32117.0    0
1      52_2.txt   9021.2   2514.24  0.72  2.71  32497.0    0
2      52_3.txt   8823.6   2616.95  0.70  2.71  31956.0    0
3      52_4.txt   9137.6   2691.43  0.71  2.71  31835.0    0
4      52_5.txt  10045.0   2894.75  0.71  2.71  36371.0    0
..          ...      ...       ...   ...   ...      ...  ...
103  52_104.txt  38116.0  19539.50  0.49  2.71  31618.0    0
104  52_105.txt  38776.4  20881.16  0.46  2.71  34644.0    0
105  52_106.txt  41786.2  19877.79  0.52  2.71  34435.0    0
106  52_107.txt  39306.6  20820.92  0.47  2.71  35185.0    0
107  52_108.txt  41325.2  19523.64  0.53  2.71  35701.0    0

[108 rows x 7 columns]

In [76]:
url_file=f"result/lsr_std_math.txt"

df = pd.read_csv(url_file,header=None, sep=';')

table = pd.DataFrame()
table = pd.concat([table, df], ignore_index=True)
table.columns = ['instance','rf','time_rf','fop','time_fop']
table['time_total'] = table['time_rf']+table['time_fop']

table_rf_fop = table
table_rf_fop

       instance       rf  time_rf      fop  time_fop  time_total
0      52_1.txt   8915.4     0.76   8751.6      1.02        1.78
1      52_2.txt   8908.0     0.82   8852.8      1.44        2.26
2      52_3.txt   8648.6     0.74   8631.4      0.81        1.55
3      52_4.txt   9227.0     0.80   9076.6      1.34        2.14
4      52_5.txt   9758.5     0.96   9758.5      1.26        2.22
..          ...      ...      ...      ...       ...         ...
103  52_104.txt  39973.5     0.36  38400.0      0.31        0.67
104  52_105.txt  40533.0     0.35  39099.8      0.31        0.66
105  52_106.txt  45220.6     0.39  41933.6      0.33        0.72
106  52_107.txt  39315.8     0.34  38988.2      0.30        0.64
107  52_108.txt  43407.2     0.38  40813.2      0.31        0.69

[108 rows x 6 columns]

In [77]:
print(np.round(table_rf_fop['time_total'].max(),2))
print(np.round(table_rf_fop['time_total'].mean(),2))

2.71
1.05

In [78]:
table_resume = pd.DataFrame()
table_resume['dif1'] = table_first_feasible['objval'] - table_rf_fop['fop']
table_resume['dif2'] = table_feasible_tlimited_mean['objval'] - table_rf_fop['fop']
table_resume['dif3'] = table_feasible_tlimited_max['objval'] - table_rf_fop['fop']
table_resume

        dif1   dif2   dif3
0     4019.2  235.4  115.2
1     3975.0  344.6  168.4
2     4766.6  430.2  192.2
3     4336.8  276.8   61.0
4     4178.0  465.0  286.5
..       ...    ...    ...
103  81559.5 -204.5 -284.0
104  89911.4 -323.4 -323.4
105  77046.4 -147.4 -147.4
106  89982.2  318.4  318.4
107  78338.8  539.2  512.0

[108 rows x 3 columns]

In [79]:
positive_count_dif1 = (table_resume['dif1'] > 0).sum()
positive_count_dif2 = (table_resume['dif2'] > 0).sum()
positive_count_dif3 = (table_resume['dif3'] > 0).sum()
print(f"Positive values in column 'dif1': {positive_count_dif1}")
print(f"Positive values in column 'dif2': {positive_count_dif2}")
print(f"Positive values in column 'dif3': {positive_count_dif3}")

Positive values in column 'dif1': 108
Positive values in column 'dif2': 74
Positive values in column 'dif3': 57

In [80]:
def tabela_mip(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','objval','bound','gap','time','nodes','opt']
    table = table[['instance','bound','objval','gap','time','nodes','opt']]

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'c52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'c52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'bound':tab['bound'].mean(),
            'objval':tab['objval'].mean(),
            #'gap':tab.loc[table['opt'] == 0,'gap'].mean(),
            #'time':tab.loc[table['opt'] == 1,'time'].mean(),
            'gap':tab['gap'].mean(),
            'time':tab['time'].mean(),
            'nodes':tab['nodes'].mean(),
            'opt':tab['opt'].sum(),
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [81]:
def tabela_math(url_file):
    
    df = pd.read_csv(url_file,header=None, sep=';')

    table = pd.DataFrame()
    table = pd.concat([table, df], ignore_index=True)
    table.columns = ['instance','rf','time_rf','fop','time_fop']
    table['time_total'] = table['time_rf']+table['time_fop']

    table['grupo'] = 'grupo' 
   
    table_result = pd.DataFrame()

    contador  = 1
    set_cont = 1
    while True:
        set_ ='set0{}'.format(str(set_cont))
        tab = pd.DataFrame()
        for i in range(contador, contador+12):
            t = table.loc[table['instance'] == f'c52_{i}.txt']
            tab = pd.concat([tab,t])
            table.loc[table[table['instance'] == f'c52_{i}.txt'].index,'grupo'] = set_
            
        
        tab = pd.DataFrame({
            'instance':f'{set_}',
            'rf':tab['rf'].mean(),
            'time_rf':tab['time_rf'].mean(),
            'fop':tab['fop'].mean(),
            'time_fop':tab['time_fop'].mean(),
            'time_total':tab['time_total'].mean()
            },index=[f'std']
        )


        if table_result.shape[0] == 0:
            table_result = tab.copy(deep=True)
        else:
            table_result = pd.concat([table_result,tab])

        contador = contador + 12
        set_cont = set_cont + 1

        if set_cont > 9 :
            break

    return table_result.reset_index(drop=True), table

In [82]:
file=f"result/lsr_std_mip_feasible_first.txt"

table_feasible_first, table_feasible_first = tabela_mip(file)

In [86]:
file=f"result/lsr_std_mip_feasible_first_tlimited_mean.txt"

table_feasible_tlimited, table_feasible_tlimeted_ = tabela_mip(file)

In [87]:
table_feasible_first = table_feasible_first[['instance','objval','time']]
table_feasible_first

       instance    objval  time
0      52_1.txt   12770.8   0.0
1      52_2.txt   12827.8   0.0
2      52_3.txt   13398.0   0.0
3      52_4.txt   13413.4   0.0
4      52_5.txt   13936.5   0.0
..          ...       ...   ...
103  52_104.txt  119959.5   0.0
104  52_105.txt  129011.2   0.0
105  52_106.txt  118980.0   0.0
106  52_107.txt  128970.4   0.0
107  52_108.txt  119152.0   0.0

[108 rows x 3 columns]

In [88]:
table_feasible_tlimited

  instance  bound  objval  gap  time  nodes  opt
0    set01    NaN     NaN  NaN   NaN    NaN    0
1    set02    NaN     NaN  NaN   NaN    NaN    0
2    set03    NaN     NaN  NaN   NaN    NaN    0
3    set04    NaN     NaN  NaN   NaN    NaN    0
4    set05    NaN     NaN  NaN   NaN    NaN    0
5    set06    NaN     NaN  NaN   NaN    NaN    0
6    set07    NaN     NaN  NaN   NaN    NaN    0
7    set08    NaN     NaN  NaN   NaN    NaN    0
8    set09    NaN     NaN  NaN   NaN    NaN    0

In [90]:
file=f"result/lsr_std_math.txt"

table_result_math, table_math = tabela_math(file)

In [17]:
table_result_math

  instance  rf  time_rf  fop  time_fop  time_total
0    set01 NaN      NaN  NaN       NaN         NaN
1    set02 NaN      NaN  NaN       NaN         NaN
2    set03 NaN      NaN  NaN       NaN         NaN
3    set04 NaN      NaN  NaN       NaN         NaN
4    set05 NaN      NaN  NaN       NaN         NaN
5    set06 NaN      NaN  NaN       NaN         NaN
6    set07 NaN      NaN  NaN       NaN         NaN
7    set08 NaN      NaN  NaN       NaN         NaN
8    set09 NaN      NaN  NaN       NaN         NaN

In [ ]:
tab = pd.DataFrame({
    'instance':f'res_mip',
    #'lb':table_result_std['lb'].mean(),
    'ub':table_result_std['ub'].mean(),
    #'gap':table_result_std['gap'].mean(),
    'time':table_result_std['time'].mean(),
    #'nodes':table_result_std['nodes'].mean(),
    'opt':table_result_std['opt'].sum(),
    },index=[f'res_mip_std']
)

res_mip_std = pd.concat([table_result_std, tab], ignore_index=True)
#res_mip_std

print(res_mip_std[['instance','ub','time']].to_latex(index=False,float_format="%.2f"))

NameError: name 'table_result_std' is not defined

In [91]:
file=f"result/lsr_std_mip_default.txt"

df = pd.DataFrame()
df = pd.read_csv(file,header=None,sep=';')

#df
tab = pd.DataFrame()
tab = pd.concat([tab, df], ignore_index=True)
tab.columns = ['instance','bound','objval','gap','time','nodes','opt']
#tab

resume = pd.DataFrame({
    'instance':f'resume',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=["resume"]
)

tab = pd.concat([tab, resume], ignore_index=True)

mip_std = tab
mip_std

,instance,bound,objval,gap,time,nodes,opt
0,52_1.txt,8698.800000,8698.80000,0.000000,12.160000,20827.000000,1
1,52_2.txt,8781.800000,8781.80000,0.000000,36.700000,92569.000000,1
2,52_3.txt,8541.600000,8541.60000,0.000000,4.370000,8093.000000,1
3,52_4.txt,8943.800000,8943.80000,0.000000,37.850000,95366.000000,1
4,52_5.txt,9717.000000,9717.00000,0.000000,206.090000,392059.000000,1
...,...,...,...,...,...,...,...
104,52_105.txt,38622.800000,38622.80000,0.000000,4.770000,3592.000000,1
105,52_106.txt,40310.400000,40310.40000,0.000000,10.700000,8824.000000,1
106,52_107.txt,38611.200000,38611.20000,0.000000,5.110000,4076.000000,1
107,52_108.txt,39826.200000,39826.20000,0.000000,3.240000,2114.000000,1
108,resume,20708.365741,20707.70463,0.000093,86.429074,145804.861111,107

In [101]:
set_ = 'set01'

tab = pd.DataFrame()
for i in range(1,13):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set01_mip = tab
set01_mip

 instance   bound   objval       gap        time      nodes  opt
    set01  9680.2  9674.25  0.000833  420.275833  708263.75   11

In [102]:
set_ = 'set02'

tab = pd.DataFrame()
for i in range(13,25):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set02_mip = tab
set02_mip

 instance         bound        objval  gap        time      nodes  opt
    set02  13530.833333  13530.833333  0.0  160.616667  281019.25   12

In [103]:
set_ = 'set03'

tab = pd.DataFrame()
for i in range(25,37):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set03_mip = tab
set03_mip

 instance         bound        objval  gap       time         nodes  opt
    set03  24430.291667  24430.291667  0.0  19.296667  25153.833333   12

In [104]:
set_ = 'set04'

tab = pd.DataFrame()
for i in range(37,49):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set04_mip = tab
set04_mip

 instance         bound        objval  gap       time     nodes  opt
    set04  12843.641667  12843.641667  0.0  10.755833  21227.25   12

In [105]:
set_ = 'set05'

tab = pd.DataFrame()
for i in range(49,61):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set05_mip = tab
set05_mip

 instance      bound     objval  gap        time          nodes  opt
    set05  16826.475  16826.475  0.0  123.601667  226197.333333   12

In [110]:
set_ = 'set06'

tab = pd.DataFrame()
for i in range(61,73):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set06_mip = tab
set06_mip

 instance    bound   objval  gap       time     nodes  opt
    set06  27706.9  27706.9  0.0  35.329167  43102.75   12

In [111]:
set_ = 'set07'

tab = pd.DataFrame()
for i in range(73,85):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set07_mip = tab
set07_mip

 instance         bound        objval  gap   time        nodes  opt
    set07  20334.816667  20334.816667  0.0  1.425  1795.916667   12

In [112]:
set_ = 'set08'

tab = pd.DataFrame()
for i in range(85,97):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set08_mip = tab
set08_mip

 instance     bound    objval  gap      time   nodes  opt
    set08  24661.75  24661.75  0.0  2.195833  2259.5   12

In [113]:
set_ = 'set09'

tab = pd.DataFrame()
for i in range(97,108):
    t = mip_std.loc[mip_std['instance'] == f'52_{i}.txt']
    tab = pd.concat([tab,t])

tab = pd.DataFrame({
    'instance':f'{set_}',
    'bound':tab['bound'].mean(),
    'objval':tab['objval'].mean(),
    'gap':tab['gap'].mean(),
    'time':tab['time'].mean(),
    'nodes':tab['nodes'].mean(),
    'opt':tab['opt'].sum(),
    },index=[f'']
)

set09_mip = tab
set09_mip

 instance         bound        objval  gap      time        nodes  opt
    set09  36045.309091  36045.309091  0.0  4.467273  3325.090909   11

In [114]:
res_mip = pd.DataFrame()
res_mip = pd.concat([res_mip,set01_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set02_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set03_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set04_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set05_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set06_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set07_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set08_mip], ignore_index= True)
res_mip = pd.concat([res_mip,set09_mip], ignore_index= True)
#res_mip

In [115]:
tab = pd.DataFrame({
    'instance':f'res_mip',
    'bound':res_mip['bound'].mean(),
    'objval':res_mip['objval'].mean(),
    'gap':res_mip['gap'].mean(),
    'time':res_mip['time'].mean(),
    'nodes':res_mip['nodes'].mean(),
    'opt':res_mip['opt'].sum(),
    },index=[f'res_mip']
)

res_mip = pd.concat([res_mip, tab], ignore_index=True)
res_mip

#print(res_mip[['instance','bound','objval','gap','time','nodes','opt']].to_latex(index=False,float_format="%.2f"))

,instance,bound,objval,gap,time,nodes,opt
0,set01,9680.200000,9674.250000,0.000833,420.275833,708263.750000,11
1,set02,13530.833333,13530.833333,0.000000,160.616667,281019.250000,12
2,set03,24430.291667,24430.291667,0.000000,19.296667,25153.833333,12
3,set04,12843.641667,12843.641667,0.000000,10.755833,21227.250000,12
4,set05,16826.475000,16826.475000,0.000000,123.601667,226197.333333,12
5,set06,27706.900000,27706.900000,0.000000,35.329167,43102.750000,12
6,set07,20334.816667,20334.816667,0.000000,1.425000,1795.916667,12
7,set08,24661.750000,24661.750000,0.000000,2.195833,2259.500000,12
8,set09,36045.309091,36045.309091,0.000000,4.467273,3325.090909,11
9,res_mip,20673.357492,20672.696380,0.000093,86.440438,145816.074916,106